import os
import json
import time
import argparse
from typing import Any, Dict, List

from openai import OpenAI


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_INPUT_JSON = os.path.join(BASE_DIR, "data", "raw", "batch_run_results.json")
DEFAULT_OUTPUT_JSON = os.path.join(BASE_DIR, "outputs", "biographies.json")


def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(path: str, data: Any) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def clean_text(text: Any) -> str:
    if text is None:
        return ""
    return " ".join(str(text).strip().split())


def build_facts_block(facts: Dict[str, Any]) -> str:
    lines = []
    for k, v in facts.items():
        key = clean_text(k)
        val = clean_text(v)
        if key and val:
            lines.append(f"- {key}: {val}")
        elif val:
            lines.append(f"- {val}")
    return "\n".join(lines)


def build_timeline_block(timeline: List[Dict[str, Any]]) -> str:
    lines = []
    for item in timeline:
        if not isinstance(item, dict):
            continue
        year = item.get("year")
        event = clean_text(item.get("event", ""))
        location = clean_text(item.get("location", ""))

        parts = []
        if year is not None:
            parts.append(f"year={year}")
        if location:
            parts.append(f"location={location}")

        meta = f" ({', '.join(parts)})" if parts else ""
        if event:
            lines.append(f"- {event}{meta}")
    return "\n".join(lines)


def build_transcript_block(
    transcript: List[Dict[str, Any]],
    include_assistant: bool = False,
    max_user_turns: int = 12,
) -> str:
    lines = []
    user_count = 0

    for turn in transcript:
        if not isinstance(turn, dict):
            continue

        role = clean_text(turn.get("role", "")).lower()
        content = clean_text(turn.get("content", ""))

        if not content or content == "[INTERVIEW COMPLETE]":
            continue

        if role == "user":
            user_count += 1
            if user_count > max_user_turns:
                break
            lines.append(f"USER: {content}")
        elif include_assistant and role == "assistant":
            lines.append(f"ASSISTANT: {content}")

    return "\n".join(lines)


def build_prompt(persona: Dict[str, Any], include_assistant: bool = False) -> str:
    persona_id = clean_text(persona.get("persona_id", ""))
    name = clean_text(persona.get("name", ""))

    facts = persona.get("facts", {}) or {}
    timeline = persona.get("timeline", []) or []
    transcript = persona.get("transcript", []) or []
    open_threads = persona.get("open_threads", []) or []

    facts_block = build_facts_block(facts)
    timeline_block = build_timeline_block(timeline)
    transcript_block = build_transcript_block(
        transcript,
        include_assistant=include_assistant,
        max_user_turns=12,
    )

    gaps_block = "\n".join(f"- {clean_text(x)}" for x in open_threads[:10] if clean_text(x))

    return f"""
You are writing a grounded biography from interview evidence.

Write a concise biography for this persona using ONLY the material provided below.

Rules:
1. Do not invent names, dates, places, jobs, family members, or life events.
2. If a detail is uncertain, preserve uncertainty using wording like:
   - "around"
   - "approximately"
   - "the speaker recalled"
   - "the interview suggests"
3. Prefer the structured facts and timeline when available.
4. Use transcript details to enrich the narrative, but never go beyond the supplied evidence.
5. Keep the biography chronological and readable.
6. Do not mention "facts", "timeline", "transcript", or "open threads" in the biography.
7. Do not mention that this was generated by AI.
8. If something is missing, leave it out rather than guessing.

Output format:
Return valid JSON with exactly these keys:
{{
  "biography": "<biography text>",
  "evidence_gaps": ["<gap 1>", "<gap 2>"]
}}

Persona ID: {persona_id}
Name: {name}

FACTS:
{facts_block if facts_block else "- None"}

TIMELINE:
{timeline_block if timeline_block else "- None"}

TRANSCRIPT EXCERPTS:
{transcript_block if transcript_block else "- None"}

OPEN THREADS / MISSING DETAILS:
{gaps_block if gaps_block else "- None"}
""".strip()


def call_model(
    client: OpenAI,
    model: str,
    prompt: str,
    temperature: float = 0.2,
) -> Dict[str, Any]:
    response = client.responses.create(
        model=model,
        temperature=temperature,
        input=[
            {
                "role": "system",
                "content": [
                    {
                        "type": "input_text",
                        "text": "You are a careful biographical writer. Follow the user's requested JSON format exactly."
                    }
                ],
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": prompt
                    }
                ],
            },
        ],
    )

    text = response.output_text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # fallback: wrap raw output
        return {
            "biography": text,
            "evidence_gaps": []
        }


def generate_biographies(
    input_json: str,
    output_json: str,
    model: str,
    temperature: float,
    include_assistant: bool,
    limit: int | None,
    sleep_seconds: float,
) -> None:
    personas = load_json(input_json)
    if not isinstance(personas, list):
        raise ValueError("Input JSON must be a list of persona records.")

    if limit is not None:
        personas = personas[:limit]

    client = OpenAI()

    results = []
    total = len(personas)

    for idx, persona in enumerate(personas, start=1):
        persona_id = clean_text(persona.get("persona_id", ""))
        name = clean_text(persona.get("name", ""))

        print(f"[{idx}/{total}] Generating biography for {persona_id} - {name}")

        prompt = build_prompt(persona, include_assistant=include_assistant)
        model_output = call_model(
            client=client,
            model=model,
            prompt=prompt,
            temperature=temperature,
        )

        biography = clean_text(model_output.get("biography", ""))
        evidence_gaps = model_output.get("evidence_gaps", [])
        if not isinstance(evidence_gaps, list):
            evidence_gaps = []

        record = {
            "persona_id": persona_id,
            "name": name,
            "biography": biography,
            "evidence_gaps": [clean_text(x) for x in evidence_gaps if clean_text(x)],
            "source_counts": {
                "facts": len(persona.get("facts", {}) or {}),
                "timeline_items": len(persona.get("timeline", []) or []),
                "transcript_turns": len(
                    [
                        t for t in (persona.get("transcript", []) or [])
                        if isinstance(t, dict)
                        and clean_text(t.get("role", "")).lower() == "user"
                        and clean_text(t.get("content", ""))
                        and clean_text(t.get("content", "")) != "[INTERVIEW COMPLETE]"
                    ]
                ),
            },
        }
        results.append(record)

        save_json(output_json, results)

        if sleep_seconds > 0:
            time.sleep(sleep_seconds)

    print(f"\nDone. Saved biographies to: {output_json}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-json", default=DEFAULT_INPUT_JSON)
    parser.add_argument("--output-json", default=DEFAULT_OUTPUT_JSON)
    parser.add_argument("--model", default="gpt-5.2")
    parser.add_argument("--temperature", type=float, default=0.2)
    parser.add_argument("--include-assistant", action="store_true")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--sleep-seconds", type=float, default=0.0)
    args = parser.parse_args()

    generate_biographies(
        input_json=args.input_json,
        output_json=args.output_json,
        model=args.model,
        temperature=args.temperature,
        include_assistant=args.include_assistant,
        limit=args.limit,
        sleep_seconds=args.sleep_seconds,
    )


if __name__ == "__main__":
    main()